<?php

namespace Sunshine\UIBundle\Repository;

/**
 * TwigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwigRepository extends \Doctrine\ORM\EntityRepository
{
}
