<?php

namespace Sunshine\OrganizationBundle\Repository;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * BusinessUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessUnitRepository extends NestedTreeRepository
{
    /**
     * @param $name
     * @return array
     */
    public function findByCompanyName($name)
    {
        $qb = $this->createQueryBuilder('bu')
            ->select('bu')
            ->join('bu.company','company')
            ->where('company.name = :name')
            ->setParameter('name', $name)
            ->getQuery()->getResult();

        return $qb;
    }

    /**
     * @param string $companyName
     * @param string $businessUnitName
     * @return mixed
     */
    public function findByCompanyAndBUName($companyName, $businessUnitName)
    {
        $qb = $this->createQueryBuilder('bu')
            ->select('bu')
            ->join('bu.company', 'company')
            ->where('company.name = :companyName')
            ->setParameter('companyName', $companyName)
            ->andWhere('bu.name = :businessUnitName')
            ->setParameter('businessUnitName', $businessUnitName)
            ->getQuery()->getOneOrNullResult();

        return $qb;
    }
}
