<?php

namespace Sunshine\OrganizationBundle\Repository;

/**
 * OrganizationRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
