<?php

namespace Sunshine\OrganizationBundle\Repository;

/**
 * ServiceGradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceGradeRepository extends \Doctrine\ORM\EntityRepository
{
}
