<?php

namespace Sunshine\OrganizationBundle\Repository;

/**
 * TitleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TitleRepository extends \Doctrine\ORM\EntityRepository
{
}
