<?php

namespace Sunshine\OrganizationBundle\Repository;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserLoaderInterface
{
    public function loadUserByUsername($username)
    {
        return $this->createQueryBuilder('u')
            ->where('u.username = :username OR u.mobile = :mobile')
            ->setParameter('username', $username)
            ->setParameter('mobile', $username)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
