<?php

namespace Sunshine\OrganizationBundle\Repository;

/**
 * WorkGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
