<?php

namespace Sunshine\AdminBundle\Repository;

/**
 * EnumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnumRepository extends \Doctrine\ORM\EntityRepository
{
}
